### ISSUE TITLE
File write fails / command line

### ISSUE THREAD

**Issue by APoStat** [sdcTools/UserSupport#36]
SDC tool used: tau-Argus
Version used: 4.1.3 build 1
Operating system used: Windows 7 Pro

When repeatedly calling tau-Argus in command line using a batch file ( .bat-file) supressed output file comes out empty occationally. There has been cases (larger hierarcy tables) where csv is only partly written. See example tautest.zip attached (check path of TauArgus.exe & test files before run): When batch.bat is run some of supressed output files (..out_5_1.csv, not included) are empty (size of 0 bytes). Sometimes csv is written ok but rda comes out empty. If csv fails rda is missing. When failed commands are run separately everything works.

[tautest.zip](https://github.com/sdcTools/UserSupport/files/631283/tautest.zip)

**Comment by ppdewolf** [comment]
Not sure yet what you mean with rda is missing or comes out empty. rda-file is input-file and is not constructed by tau-argus?

**Comment by APoStat** [comment]
Normally, when everything goes well, I get except file ..._out_5_1.csv, also files _out_5_1.rda and _out_5_1.html. In my example html always comes out ok but occationally csv and/or rda fails.

**Comment by AncoHundepool** [comment]
The problem should be solved in your batch-file.
In your bat-file the different calls to TAU-ARGUS will run simultaneously on your computer. This will cause conflicts with temporary file in your temp-directory.

However if you specify 
start /wait "C:\Program Files (x86)\TauArgus\TauArgus.exe" D:\UD\tautest\files\p_0001.ARB
each call to TAU-ARGUS will wait for the previous one before it will be started.

I assume that this will solve your problem.
Please give it a try and let us know
[batch_AH.zip](https://github.com/sdcTools/UserSupport/files/661907/batch_AH.zip)

**Comment by APoStat** [comment]
Thanks for an answer. I tried 'start-wait' method (zip attached, I had to add a title in each call). Unfortunately I still get some erroneous ..out_5_1.csv/rda output files, even though not so many. Additionally I tried to delay next tauArgus call by adding 'ping 127.1.1.1 -n 2 > nul' after each call but it didn't help.
[tautest.zip](https://github.com/sdcTools/UserSupport/files/696283/tautest.zip)

**Comment by ppdewolf** [comment]
When I run your example, I get all 149 output files (...out_5_1.csv/rda/html and ...log).
What do you mean with "some erroneous output files"? Wrong content, or no output file at all?

**Comment by APoStat** [comment]
Csv is allways generated but sometimes it is size of 0 bytes (it is empty). Sometimes csv is greater than 0 bytes but only partly written to disk. When csv-writing to disk fails, no rda is generated. 

Sometimes csv is written to disk ok but rda is missing.

Every time I run my example, I get few output files size of 0 (csv or rda). My version 4.1.3 build 1 doesn't generate log-file at all. We have tested in several computers: Windows 7 Pro 64 bit, tested also with 32-bit java compiler.

**Comment by ppdewolf** [comment]
Is this now solved, as suggested in comment by Anco on issue #58?
Re-open if not.

**Comment by APoStat** [comment]
Attached is an example where I try to protect two additive tables within one .arb file via TauArgus/File/Open Batch Process. First protected table is only partly written into .csv output file.

Both input datas are similar. Result is ok if I protect only one of them in arb.

[tautest_b.zip](https://github.com/sdcTools/UserSupport/files/1453914/tautest_b.zip)

**Comment by ppdewolf** [comment]
Could you check if this only happens when saving as intermediate format (as you do in your arb-file)?

By the way: TR+ does not do anything for intermediate format (it is also not enabled in interactive mode).

**Comment by APoStat** [comment]
Other formats works fine! But unfortunately I need intermediate format for certain reasons...

**Comment by ppdewolf** [comment]
Thanks, just wanted to check. This supports my suspicion about the underlying problem in the code. I'll look into it.

**Comment by AncoHundepool** [comment]
With respect to TR+: please note that we simply skip non-relevant options in the WRITETABLE command.
Equivalent to disabling it in the interactive mode. It would imply a lot of coding and we think it is more convenient to the user.

**Comment by ppdewolf** [comment]
Will be solved in release 4.1.7

**Comment by APoStat** [comment]
Is there a way to get the repair in use right away?

**Comment by ppdewolf** [comment]
I intent to have the next release (4.1.7) before the end of this year (2017).

Unfortunately not possible to get without a complete new release (interaction between codes of different parts).

The mentioned solution is for saving incomplete files with intermediate format, when applied in batch with multiple/many tables/runs. Not for the TR+ part.

**Comment by ppdewolf** [comment]
I've just launched a pre-release of version 4.1.7 to be tested: [Pre release 4.1.7](https://github.com/sdcTools/tauargus/releases/tag/4.1.7) 
So, if you feel lucky, you can try testing 😃
