### ISSUE TITLE
<READTABLE> an empty cell cannot have a real frequency (err >= 4.1.5)

### ISSUE THREAD

**Issue by bernhard-da** [sdcTools/UserSupport#65]
**SDC tool used:** tau-argus
**Version used:**  4.1.6 (test-version)
**Operating system used:** windows
---

running [**this example**](https://github.com/sdcTools/checkTauArgus/tree/master/inst/tests/Batch/ex1) from [**checkTauArgus**](https://github.com/sdcTools/checkTauArgus/tree/master/inst/tests/Batch/ex1)  used to work with release 4.1.4_updated, but fails with this testing-release (and also with 4.1.5). The error in the log-file is:

```
Error in file Y:\rstudio_projects\checkTauArgus\inst\tests\Batch\ex1\tabdata_ex1.tab on line 1.
Line = Total, Total,5146,S,1,1
An empty cell cannot have a real frequency
```
have there been any relevant changes in parsing the input-data?

**Comment by AncoHundepool** [comment]
I looked into this. But when I tried to download the files I saw that not all files had a proper windows Newline. We expect a CrLf. I had problems with the rda file.
When I corrected this I could run this table.

Nevertheless the error message is weird and we should find the cause. But if I run your RDA fie I get an other more meaningful error.

In the previous version I remember that we sometimes added the complete CrLf if something was missing, but not now

**Comment by bernhard-da** [comment]
hi anco, thx for responding. unfortunately, i am a bit stuck on this. i changed all line-endings to crlf in all the input files but i still get the same error (`An empty cell cannot have a real frequency`) in 4.1.6 (test) and 4.1.5  and in this case also in 4.1.4!

as soon as i change the line-endings in the two hrc-files to lf, 4.1.4 works again but not >= 4.1.5. I then tried all the combinations (rda-, tab- and arb-file with lf or crlf endlings) but was not able to run the problem successfully with >=4.1.5 always resulting in the same error. 

which more meaningful error did you get?

**Comment by AncoHundepool** [comment]
Hi Bernard.

When I changed the RDA file the table could be read easily from the GUI. So I though fine.

But in Batch your problem is still there. No idea yet.

**Comment by AncoHundepool** [comment]
Something goes wrong in the interpretation of the <freq> in the <SPECIFYTABLE>. That is the problem here.

**Comment by LMeglen** [comment]
Hi,
I tested tabular data in Tau Argus 4.1.6. I have problems too with dots in tabular data. See the ateched file.

[Test_tabular_data.docx](https://github.com/sdcTools/UserSupport/files/1108717/Test_tabular_data.docx)

**Comment by AncoHundepool** [comment]
Your first problem is whether or not we should accept a . as a zero? Opinions please!!!
Your second problem leads to a misleading message, but basically your  resp. = empty and the status is safe; Do we think that that is acceptable. Or should is be a status empty?

**Comment by bernhard-da** [comment]
@AncoHundepool I can confirm that manually defining the table in the GUI works in 4.1.6 while using the batch-file does not.

**Comment by ppdewolf** [comment]
@bernhard-da and @AncoHundepool 
The example has no response variable, only a frequency variable. Since only a frequency table is looked at, that should be okay, but apparently in batch a response variable is required, even if not used.

In batch we do not know when reading the table that we will only deal with a frequency table.
Workaround: define the response variable as being the frequency variable: [metadata_ex1.rda.txt](https://github.com/sdcTools/UserSupport/files/1111233/metadata_ex1.rda.txt)

**Comment by bernhard-da** [comment]
@ppdewolf thx for the workaround which indeed works!

but what why has this behaviour changed since 4.1.4? any reasons for this?

**Comment by AncoHundepool** [comment]
Dear Bernard, Thanks for helping. The real problem is, as far as I can see now, that the <FREQ> in the <SPECIFYTABLE> command is not treated correctly. We must solve that.

By the way: the missing value in your freq variable is meaningless. We do nothing with that and in fact I want to forbid it or at least issue a warning.
By the way, the missings in the explanatory variable s are not required. You can omit them if you do not need them and these extra empty columns and rows will be removed.

**Comment by bernhard-da** [comment]
@anco thx, i thought this was required, apparently it is not, even better :)

@ppdewolf i just had a look in the log-file using your approach (defining the frequency variable as numeric in the metadataset and using this variable as response-variable in the `<SPECIFYTABLE>` expression. as you can see in the [**here**](https://gist.github.com/bernhard-da/5344be13cae0bc0bda6e3faac865be99), there are entries 

`A real cell with no frequency is strange; In cell (x,y) freq = 1 has been imputed` 
for each cell which are not present in 4.1.4 (but already in 4.1.5). however, the resulting table seems to be ok. my question: why is this warning?

another thing: I tried to overcome the problem by just adding a dummy variable having a value of 1 for each cell) and defining this variable as `<NUMERIC>` in the rda file and keeping everything else the same, see [**here**](https://gist.github.com/bernhard-da/ac66e031084f938085ddb42119983d48). however, i get the following error in each version:

`Table is not additive` 

do you have an idea why this does not work?

**Comment by ppdewolf** [comment]
One of the changes between 4.1.4 and later versions is the way we try to deal with "strange"  situations with tabular input. For a long time microdata input has been given te most attention (in our view still the best way to go ;-) ), later tabular input has become more popular. 
In 4.1.4 (and before) some "ad-hoc"-solutions were implemented that did a nice job. However, introducing some more restrictive checks sometimes gives more warnings and/or errors compared to 4.1.4. That might explain some of the differences. We certainly need to take some more time to check the checks ;-)

About "the other  thing": that input is clearly a non-additive table (totals are not the sum of underlying cells). And tau does not like non-additive tables. You could use `<READTABLE> 2` to allow for non-additivity (what should result in a warning that modular and optimal may give strange results on non-additive tables).
This however will show that using the `<freq>` as response variable in this way does not give the frequency table. This is something related to the comments from @AncoHundepool where he states that the `<freq>` is not dealt with correctly. We're working on that.

**Comment by bernhard-da** [comment]
@ppdewolf that makes of course sense, thx!

about your second remark. I do not understand why the table is "clearly non-additive". 

as i understood the manual, it should work as follows: a variable having an attribute `<FREQUENCY>` in the rda-file indicates (to argus) the number of records making up the cell total. `<freq>` would then take this information into account when it is used in a `<SPECIFYTABLE>` statement. in the example, i was referring to, the variable `freq` has this attribute and is clearly additive in the tabular inputdata set and I was not expecting a non-additive table. 

after some experiments, it seems to me that if more than one possible response-variable is available from in the rda-file (e.g multiple variables with attribute `<NUMERIC>`), argus always chooses the variable as response variable that occurs last, independent on the setting in `<SPECIFYTABLE>` when using a batch-file.

anyway, i'll wait what you come up with :)

**Comment by ppdewolf** [comment]
I now see why this is confusing ;-( 
Some of the batch-commands behave differently for microdatainput as compared to tabular data input.

The `<SPECIFYTABLE>` command can be used in batch-mode for microdata input and for tabular input. In case of microdata input your understanding of the manual is correct: you can specify the response variable you want to use. In case of tabular data input, only a single response variable is assumed: tabular input is a single table, hence only has one response variable. This also reflects the GUI: in case of tabular input you can not select a specific response variable. 

With tabular data input, we currently assume that there is a response variable present. The "dummy" variable you added as response variable was "clearly non-additive" ;-)

We added the `<FREQUENCY>` variable to be able to have argus apply the minimum frequency rule in case of tabular input (i.e. , not using "use given status"). But I think that using the `<FREQUENCY>` variable to produce a frequency table should be an interesting option.

We should thus make things more clear in the manual, or add some more features ;-)

**Comment by bernhard-da** [comment]
@ppdewolf  thx, now everything is much clearer!

**Comment by junoslukan** [comment]
Dear all,

Thank you very much for looking into this. 

Just a general comment regarding the zero or empty cells (the problems that @LMeglen posted). We would prefer if the rules for defining zeros or missing values in tab files would change as little as possible going from one (minor) revision of Tau-Argus to the next. This is because we are using tab files as parts of larger programmes (such as SAS-tool) and any change made to how Tau-Argus deals with tab files needs to be accounted for in our own programmes as well.

If such a change is deemed necessary, we would kindly ask that it is clearly documented.

**Comment by AncoHundepool** [comment]
We are not considering any changes at the moment. We will try to solve the problems, reading a freq-table in batch.
AND:
We will not accept a . as a numeric value. Also because a dot is often used in statistical publications as a special character for something like not available or so. 
Also an empty value for a response value like Meglen tried is not acceptable. An empty cell will not be eligible for suppression. So Why should we have protection levels.
In fact you might be looking for a non-structural empty cell. Maybe we should introduce that in the future, but that needs some discussion first.

**Comment by AncoHundepool** [comment]
The FREQ is now accepted in the READTABLE command. This solves also the strange error message about an empty cell.

Nevertheless we must be clear about what is an empty cell or not. I think that it is strange that an empty cell can have some real values on the additional variables, like frequency or protection levels. 
An empty cell is a cell where nothing happens and is also excluded when searching the secondaries.
The best way to enter an empty cell is to simply not including it in the .TAB file.  There is no obligation to enter all cells in the TAB-file. Also the status "E" could be used if you really need to enter these cells.
